"""empty message

Revision ID: 2f5afe7e2654
Revises: fd09af7fd0b2
Create Date: 2023-09-29 16:18:20.285288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5afe7e2654'
down_revision: Union[str, None] = 'fd09af7fd0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('welcome_photo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_column('welcome_photo')

    # ### end Alembic commands ###
