"""empty message

Revision ID: ef602a0732d4
Revises: f0be36f3fbbe
Create Date: 2023-09-29 01:02:23.376888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef602a0732d4'
down_revision: Union[str, None] = 'f0be36f3fbbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
